name: Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select the tag'
        required: true
        options: ${{ steps.get_tags.outputs.tagOptions }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Get Tags
        id: get_tags
        uses: actions/github-script@v4
        with:
          github-token: ${{ github.token }}
          script: |
            const response = await octokit.git.listRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              namespace: 'tags'
            });

            const tagOptions = response.data.map(tag => tag.ref.replace('refs/tags/', ''));
            console.log(`::set-output name=tagOptions::${JSON.stringify(tagOptions)}`);
