name: Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select the tag'
        required: true
        type: choice
        options: ${{ steps.get_tags.outputs.tags }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Get Tags
        id: get_tags
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: tags } = await octokit.git.listRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              namespace: 'tags'
            });
            const tagOptions = tags.map(tag => tag.ref.replace('refs/tags/', ''));
            console.log(`::set-output name=tags::${JSON.stringify(tagOptions)}`);
      
      - name: Trigger Workflow
        run: echo "Running workflow with tag: ${{ github.event.inputs.tag }}"
