name: Access Previous Job Step Output

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Select Github Version"
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      id: step1
      run: echo "::set-output name=myOutput::Hello, World!"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Step 2
      run: echo ${{ needs.job1.step1.outputs.myOutput }}
