name: Deploy Sandbox

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - canary
          - sandbox
      tag:
        description: 'Select the tag'
        required: true
        type: choice
        options: ${{ steps.get_tags.outputs.tags }}

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
    - name: Get Tags
      id: get_tags
      run: |
        tags=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/tags | jq -r '.[].name')
        echo "::set-output name=tags::$tags"
    - name: Selected Version and Environment
      run: |
        environment=${{github.event.inputs.environment}}
        version=${{github.event.inputs.tag}}
        echo "environment=$environment" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
