name: Deploy Sandbox

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - canary
          - sandbox
      release:
        description: 'Select the release'
        required: true

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
    - name: Selected Version and Environment
      run: |
        environment=${{github.event.inputs.environment}}
        version=${{github.event.inputs.release}}
        echo "environment=$environment" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
